version: '3'
services:
#mssql docker
  radvolontera-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    networks:
      - radvolonteranet

  radvolontera-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:DefaultConnection=Server=radvolontera-sql,1433;Database=RadVolontera;User=sa;Password=QWElkj132!;ConnectRetryCount=0
    ports:
      - 5010:5010
    networks:
      - radvolonteranet      
    links:
      - radvolontera-sql
    depends_on:
      - radvolontera-sql
      
networks:
  radvolonteranet:
    driver: bridge      